### ISSUE TITLE
What to do when refresh token expires

### ISSUE THREAD

**Issue by iHassanAli** [SallaApp/passport-strategy#37]
In my application, easy mode, I get the refresh token and the access token, but refresh tokens also expire after a month. How do I make the user sign in again to get new refreshtoken? Or is there an API to refresh the refresh token?

**Comment by jamalla2** [comment]
> In my application, easy mode, I get the refresh token and the access token, but refresh tokens also expire after a month. How do I make the user sign in again to get new refreshtoken? Or is there an API to refresh the refresh token?

Typically, when a refresh token expires, you need to reauthenticate the user to obtain a new refresh token. The process involves having the user sign in again and granting authorization to your application.
